[package]
name = "tiny-health-checker"
version = "0.22.0"
edition = "2021"
authors = ["Daniel Mikusa <dmikusa@vmware.com>"]
description = "A tiny health checker for use in containers with Docker health checks"

[dependencies]
rustls = "0.22"
ureq = { version = "2.9", features = ["tls"] }

[profile.release]
opt-level = "s"
lto = "fat"
strip = "symbols"

[dev-dependencies]
temp-env = "0.3"
